namespace SME.CDEP.Dominio.Constantes;

public class MensagemNegocio
{
    public const string EVENTO_NAO_ENCONTRADO = "Evento não encontrado";
    public const string EXISTE_SUSPENSAO_OU_FERIADO_NESSE_DIA = "Já existe uma suspensão ou feriado cadastrado para essa data";
    public const string DIA_INVALIDO = "Dia inválido";
    public const string MES_INVALIDO = "Mês inválido";
    public const string JUSTIFICATIVA_NAO_INFORMADA = "Justificativa não informada para a suspensão";
    public const string O_ANO_NAO_ESTA_SEGUINDO_FORMATO_ABNT = "O Ano do acervo não está seguindo o formato da ABNT";
    public const string ACERVO_NAO_ENCONTRADO = "Acervo não encontrado";
    public const string SOLICITACAO_ATENDIMENTO_NAO_ENCONTRADA = "Solicitação de atendimento não encontrada";
    public const string SOLICITACAO_ATENDIMENTO_ITEM_NAO_ENCONTRADA = "Solicitação de atendimento item não encontrada";
    public const string SITUACAO_INVALIDA_PARA_FINALIZAR = "Existem itens de acervos com situação diferente de: Aguardando visita, Finalizado automaticamente e Cancelado";
    public const string ATENDIMENTO_NAO_ESTA_AGUARDANDO_VISITA = "Não é permitido realizar a alteração da data de visita em item quando a solicitação não estiver aguardando visita";
    public const string SITUACAO_INVALIDA_PARA_CANCELAR = "O atendimento não pode ser cancelado quando os itens do acervo foram atendidos parcialmente";
    public const string SOLICITACAO_ATENDIMENTO_ITEM_NAO_CONTEM_ACERVOS = "Solicitação de atendimento não contém acervos";
    public const string TIPO_ATENDIMENTO_INVALIDO = "É necessário informar o tipo de atendimento em cada item do acervo";
    public const string ITENS_ACERVOS_PRESENCIAL_DEVEM_TER_DATA_ACERVO = "Nem todos os itens dos acervos do tipo presencial, tem data de visita";
    public const string ITENS_ACERVOS_PRESENCIAL_NAO_DEVEM_TER_DATA_ACERVO_PASSADAS = "As datas de visita dos acervos presenciais não podem ser datas passadas";
    public const string ITENS_ACERVOS_EMAIL_NAO_DEVEM_TER_DATA_ACERVO = "As datas de visita não devem ser informados nos acervos com tipo de atendimento por e-mail";
    public const string USUARIO_NAO_ENCONTRADO = "Usuário não encontrado";
    public const string O_ITEM_X_DO_DOMINIO_X_NAO_ENCONTRADO = "O item '{0}' do domínio '{1}' não foi encontrado";
    public const string SOMENTE_ARQUIVO_XLSX_SUPORTADO = "Esse arquivo não é um XLSX. Somente arquivos do tipo XLSX são permitidos";
    public const string ARQUIVO_VAZIO = "O arquivo está vazio";
    public const string SOMENTE_ACERVO_DOCUMENTAL_POSSUI_CODIGO_NOVO = "Somente acervo documental possui código novo";
    public const string ESSE_ACERVO_NAO_POSSUI_CREDITO_OU_AUTOR = "Esse acervo não possui crédito ou autor";
    public const string CREDITO_OU_AUTORES_SAO_OBRIGATORIOS = "O crédito/autor deve ser informado para esse tipo de acervo";
    public const string ARQUIVO_NAO_ENCONTRADO = "Arquivo não foi encontrada";
    public const string ARQUIVO_INF0RMADO_NAO_ENCONTRADO = "O arquivo informado não foi encontrado";
    public const string NAO_FOI_POSSIVEL_VINCULAR_PERFIL_EXTERNO_CORESSO_USUARIO_SEM_PERFIL = "Não foi possível vincular perfil Externo no CoreSSO - Usuário sem perfil";
    public const string REGISTRO_X_DUPLICADO = "Registro '{0}' duplicado";
    public const string REGISTRO_DUPLICADO = "Registro duplicado";
    public const string CAMPO_NAO_INFORMADO = "{0} não informado";
    public const string SO_EH_PERMITIDO_ALTERAR_ENDERECO_TELEFONE_DE_USUARIOS_EXTERNOS = "Só é permitido alterar endereço/telefone de usuários externos";
    public const string LOGIN_NAO_ENCONTRADO = "Login não encontrado";
    public const string LOGIN_OU_SENHA_ATUAL_NAO_COMFEREM = "Login ou senha atual não conferem";
    public const string AS_ORIENTAÇÕES_PARA_RECUPERAÇÃO_DE_SENHA_FORAM_ENVIADOS_PARA_EMAIL_VERIFIQUE_SUA_CAIXA_DE_ENTRADA = "As orientações para recuperação de senha foram enviados para {0}, verifique sua caixa de entrada!";
    public const string PERFIS_DO_USUARIO_NAO_LOCALIZADOS_VERIFIQUE_O_LOGIN = "Os perfis do usuário não foram localizados!Verifique o login.";
    public const string USUARIO_OU_SENHA_INVALIDOS = "Usuário ou senha inválidos";
    public const string A_SENHA_DEVE_CONTER_SOMENTE = "A senha deve conter pelo menos 1 letra maiúscula, 1 minúscula, 1 número e/ou 1 caractere especial e não pode conter acentuação";
    public const string A_SENHA_NAO_PODE_CONTER_ESPACOS_EM_BRANCO = "A senhão não pode conter espaço em branco";
    public const string A_SENHA_DEVE_TER_NO_MÁXIMO_12_CARACTERES = "A senha deve conter no máximo 12 caracteres";
    public const string A_SENHA_DEVE_TER_NO_MÍNIMO_8_CARACTERES = "A senha deve conter no minimo 8 caracteres";
    public const string CONFIRMACAO_SENHA_DEVE_SER_IGUAL_A_SENHA = "Confirmação da senha: Deve ser igual a senha";
    public const string NAO_FOI_POSSIVEL_CADASTRAR_USUARIO_EXTERNO_NO_CORESSO = "Não foi possível cadastrar usuário externo no CoreSSO";
    public const string VOCE_JA_POSSUI_LOGIN_ACERVO = "Você já possui login no sistema. Caso tenha esquecido a senha, clique em 'esqueci a senha'";
    public const string VOCE_JA_POSSUI_LOGIN_CORESSO = "Você já possui login no sistema. Acesse informando seu RF e senha dos Sistemas da SME (SGP ou Plateia)";
    public const string PLANILHA_VAZIA = "A planilha importada está vazia";
    public const string NAO_PERMITIDO_ANO_FUTURO = "O campo ano não admite anos futuros. Apenas anos atuais e anteriores são permitidos.";
    public const string TOKEN_INVALIDO = "Token inválido";
    public const string CAMPO_X_ESPERADO_NUMERICO_E_COM_CASAS_DECIMAIS = "É esperado que o campo '{0}' seja um numérico com duas casas decimais separados por vírgula";
}