update public.parametro_sistema set valor =
       '<span style="box-sizing:border-box; display:inline !important">	   	   		
		<p style="margin:0cm; font-size:11pt; font-family:Calibri, sans-serif; text-align:justify; background:white"><span style="font-size:10.5pt; font-family:&quot;Verdana&quot;,sans-serif; color:black">Pesquisador(a), &nbsp;</span> </p><p style="margin:0cm; font-size:11pt; font-family:Calibri, sans-serif; text-align:justify; background:white"><span style="font-size:10.5pt; font-family:&quot;Verdana&quot;,sans-serif; color:black">&nbsp;&nbsp;</span> </p><p style="margin:0cm; font-size:11pt; font-family:Calibri, sans-serif; margin:0cm; text-align:justify; background:white"><span style="font-size:10.5pt; font-family:&quot;Verdana&quot;,sans-serif; color:black">
		Os acervos da Secretaria Municipal de Educação de São Paulo estão disponíveis apenas para consulta, exceto o bibliográfico, que pode ser emprestado. O usuário é o único e exclusivo responsável pelo respeito aos direitos autorais, personalíssimos e conexos das obras pesquisadas. É vedada a reprodução de obras originais ou cópias, no todo ou em parte, de qualquer forma e para qualquer finalidade, em conformidade com a   
		</span><span style="font-size:10.5pt;  font-family:&quot;Verdana&quot;,sans-serif; color:blue"><a href="https://nam10.safelinks.protection.outlook.com/?url=http:%2f%2fwww.planalto.gov.br%2fccivil_03%2fleis%2fL9610.htm&amp;data=05%7c01%7cmarlon.goncalves%40amcom.com.br%7c042a7a1716714824ec5108dbea93f8ff%7c62803d520a0447558c886e5fcb82b92f%7c0%7c0%7c638361693521019640%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&amp;sdata=3ghBEnxg2PKKhXplkkuPYCdcvgf4bPZ%2BybLxDxmoB1I%3D&amp;reserved=0" target="_blank">Lei nº 9.610, de 19 de fevereiro de 1998</a>.</span><span style="font-size:10.5pt; font-family:&quot;Verdana&quot;,sans-serif; color:black">&nbsp;&nbsp;</span> </p><p style="margin:0cm; font-size:11pt; font-family:Calibri, sans-serif; text-align:justify; background:white"><span style="font-size:10.5pt; font-family:&quot;Verdana&quot;,sans-serif; color:black">&nbsp;&nbsp;</span> </p><p style="margin:0cm; font-size:11pt; font-family:Calibri, sans-serif; margin:0cm; text-align:justify; background:white"><span style="font-size:10.5pt; font-family:&quot;Verdana&quot;,sans-serif; color:black">
		Quando utilizado em pesquisas e trabalhos acadêmicos, dar crédito à <b>Secretaria
		Municipal de Educação de São Paulo</b>, como instituição detentora da propriedade intelectual do conteúdo pesquisado.  
		</span> </p><br>
		<p style="margin:0cm; font-size:11pt; font-family:Calibri, sans-serif; margin:0cm; text-align:justify; background:white"><span style="font-size:10.5pt; font-family:&quot;Verdana&quot;,sans-serif; color:black">
		Este termo também considera a LGPD, <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" target="_blank">Lei nº 13.709, de 14 agosto de 2018</a>, que protege não só os dados fornecidos pelo pesquisador, como aqueles fornecidos pelo CDEP. 
		</span> </p><br>
		</span>	   
	   '	   
where nome = 'TermoCompromissoPesquisador' and tipo = 1

